.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm matelcli
.Nd command-line interface to the Matrix messaging service
.Sh SYNOPSIS
.Nm matelcli
.Ar command argument
.Sh AUTHOR
.Nm matelcli
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq varikvalefor@aol.com .
