.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm matelcli
.Nd command-line interface to the Matrix messaging service
.Sh SYNOPSIS
.Nm matelcli
.Ar command argument
.Sh DESCRIPTION
.Nm matelcli
is used to perform various Matrix-related tasks via a command-line
interface, as opposed to the terminal user interface of
.Xr matel 1 .
.Pp
The benefits of this user interface include but are not limited to
scriptability, intuitiveness, and a decent number of Easter eggs.
Additionally,
.Nm matelcli
can theoretically be accessed from teletypewriters, which is cool.
.Sh LISTING STUFF
.Nm matelcli list
.Op rooms | communities | spaces
.Pp
The
.Nm list
command lists various Matrix entities.
.Pp
.Nm matelcli list rooms
lists the Matrix rooms of which the user of
.Nm matelcli
is a member.
.Pp
.Nm matelcli list communities
lists the Matrix communities of which the user of
.Nm matelcli
is a member.
.Pp
.Nm matelcli list spaces
lists the Matrix spaces of which the user of
.Nm matelcli
is a member.
.Sh SENDING MESSAGES
.Ss SENDING TEXT
.Nm matelcli send text
.Ar room
sends the text which is fetched from the standard input to the Matrix
room whose internal Matrix ID is
.Ar room .
.Pp
One advantage of using this standard input-based approach is being able
to send the contents of suitably short files as text-based messages.
Assuming that
.Pa methage
contains printable text and
.Ar dummies
is a valid internal Matrix room ID, a command which sends the content of
.Pa methage
to Matrix room
.Ar dummies
is as follows:
.Bd -literal -offset indent
matelcli send text dummies < methage
.Ed
.Pp
Additionally, using the standard input-based approach facilitates
sending arbitrary characters in the bodies of messages.
.Ss SENDING FILES
.Nm matelcli send file
.Ar path
.Ar room
sends the file whose path is
.Ar path
to the Matrix room whose internal Matrix ID is
.Ar room .
.Ss SENDING NOTICES
.Nm matelcli send notice
.Ar room
sends a
.Dq m.notice
event whose
.Dq body
content equals the standard input to the Matrix room whose internal
Matrix room ID is
.Ar room .
.Sh GRABBING PILLS, IF "PILLS" REFERS TO MESSAGES
.Nm matelcli grab
.Ar n
.Op recent | first
.Nm from
.Ar roomId
.Pp
The
.Nm grab
command is used to fetch messages from Matrix rooms.
.Pp
.Ar roomId
is of the format
.Dq #[roomname]:[homeserver] .
.Pp
.Nm matelcli grab
.Ar n
.Nm recent
.Ar roomId
fetches the
.Ar n
messages which are most recently sent to room
.Ar roomId .
.Pp
.Nm matelcli grab
.Ar n
.Nm early
.Ar roomId
fetches the
.Ar n
earliest messages of room
.Ar roomId .
.Sh MARKING MESSAGES AS HAVING BEEN READ
Where
.Ar k
is a message identifier which is known to be valid,
.Nm matelcli markread
.Ar k
marks the message whose message identifier is
.Ar k
as having been read.
.Sh ENTERING THE MATRIX
Using the username and password which are specified in Config.hs,
.Nm matelcli login
generates a new authorisation token for the user's Matrix account and
prints this authorisation token to the standard output.
.Sh SYNC
.Nm matelcli sync
.Op Ar since
.Pp
The Matrix
.Dq sync
command can be sent to the homeserver via the
.Nm matelcli
.Nm sync
command.
.Pp
If
.Ar since
is specified, then the
.Dq since
value of the
.Dq sync
request equals
.Ar since.
The
.Dq since
value is otherwise unmentioned in the
.Dq sync
request.
.Sh JOINING ROOMS
.Nm matelcli join
.Ar room
.Op Ar inviter_id token signature
.Pp
Matrix rooms are joined via the
.Nm join
command.
.Pp
If the number of arguments equals 1, then
.Nm matelcli
attempts to add the user to the room whose internal Matrix ID is
.Ar room .
.Pp
If the number of arguments equals 4, then
.Nm matelcli
attempts to add the user to the room whose internal Matrix ID is
.Ar room
such that the Matrix API query mentions the inviter's user ID
.Ar inviter_id ,
the token of the invitation
.Ar token ,
and the signature of the invitation
.Ar signature .
.Sh LEAVING ROOMS
.Nm matelcli leave
.Ar roomid
.Pp
The
.Nm leave
command is used to leave Matrix rooms.
.Pp
If command
.Nm leave Ar roomid
is entered and all goes well, then Matel's user leaves the Matrix room
whose internal ID is
.Ar roomid .
If something breaks, then a description of the breakage is output to
the standard error.
.Sh KICKING ROOM MEMBERS
.Nm matelcli kick Ar user roomid
.Pp
Assuming that Matel's user has the appropriate permissions and
everything else goes well,
.Nm matelcli kick Ar user roomid
kicks the user whose Matrix ID is
.Ar user
from the Matrix room whose internal Matrix ID is
.Ar roomid .
.Pp
If some weird error is encountered, then a description of this error is
written to the standard output.
.Sh CREATING ROOMS
.Nm matelcli
.Ar roomname topic permission ,
creates a Matrix room whose display name and topic are
.Ar roomname
and
.Ar topic ,
respectively.  If
.Ar permission
equals
.Dq private ,
then a private room is created.  If
.Ar permission
equals
.Dq public ,
then a public room is created.  If
.Ar permission
equals some other thing, then the homeserver probably responds with
whinging.
.Pp
If the desired room is actually created, then the internal Matrix ID of
the created room is written to the standard output.
.Pp
If something breaks, then a description of the breakage is written to
the standard error.
.Sh EXAMPLES
.Ss Sending a Text-Based Message
The following command sends a message whose body is
.Dq yo, you suck
to the Matrix room whose internal Matrix ID is
.Sy !junkers:matrix.org :
.Pp
.Dl  echo -n 'yo, you suck' | matelcli send text !junkers:matrix.org
.Sh AUTHOR
.Nm matelcli
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq Mt varikvalefor@aol.com .
Hate mail should be forwarded accordingly.
