.Dd $Mdocdate$
.Dt matelcli 1
.Os OpenBSD 6.9
.Sh NAME
.Nm matelcli
.Nd terminal user interface-based Matrix client
.Sh SYNOPSIS
.Sh DESCRIPTION
.Nm matel
is a terminal user interface-based client for the Matrix instant
messaging service.
.Pp
Potential users of
.Nm matel
should note that
.Nm matel
is currently pretty useless; the layout specification which is contained
within this document may change at any time... and is not even
implemented, anyway.  Until
.Nm matel
actually works, potential users of
.Nm matel
may use
.Xr matelcli 1
or
.Xr gomuks 1 .
.Sh CONFIGURATION
Before
.Nm matel
can be used,
the configuration file of
.Nm matel
must be created.  This configuration file is stored in
.Pa $HOME/.config/matel ,
and each line conforms to the format
.Dq field: content .
.Pp
Descriptions of the accepted lines of the
.Nm matel
configuration file are as follows:
.Bl -ohang -offset Ds
.It Em PROTOCOL
The content of the
.Dq protocol
field is the protocol which should be used to communicate with the Matrix homeserver.
Currently, only values of
.Dq http
and
.Dq https
are supported.  These values enable HTTP or HTTPS, respectively.
.It Em HOMESERVER
The content of the
.Dq homeserver
field is the FQDN of the homeserver of the user of
.Nm matel .
.It Em USERNAME
The content of the
.Dq username
field is the MXID of Matel's user, e.g.,
.Dq @varikvalefor:matrix.org .
.It Em PASSWORD
The content of the
.Dq password
field is the password of the Matrix account of the user of
.Nm matel .
.It Em AUTHTOKEN
The content of the
.Dq authtoken
field is the authorisation token which is used to interact on behalf of the user of
.Nm matelcli .
.El
.Sh LAYOUT
.Ss CENTRAL PANE
The central pane of the
.Nm matel
window lists the messages which are sent to the Matrix room which
is currently selected.
.Ss BOTTOM PANE
The bottom pane of the
.Nm matel
window is the box into which commands, e.g.,
.Dl /send Dq asdfasdfasdf ,
are input.
.Ss LEFT PANE
The left pane of the
.Nm matel
window lists the Matrix rooms of which
the user of
.Nm matel
is a member.
.Sh AUTHOR
.Nm matel
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq Mt varikvalefor@aol.com .
Please send feedback accordingly.
.Pp
Alternatively, VARIK can be contacted via Matrix.
VARIK's primary Matrix username is @varikvalefor:matrix.org.
